# -*- coding: utf-8 -*-
"""my_dic_list_tuple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KFJPbsk4WGu9gEh4moyUV9xpFTqH4UDm
"""

{'a':0 , 'b':'memo_oppenheimer', 'c': [0,2,6]} #I put together my own dictionary

my_dic = {'a': 0, 'b': 'memo_oppenheimer', 'c': [0, 2, 6]} #"I'm going to assign this dictionary to a variable called my_dictionary so that I can easily access it throughout my program."

my_dic   #Tip:Variable names in Python cannot start with a number.

my_dic['b']   # I accessed each element in my dictionary.

my_dic['a']   # I accessed each element in my dictionary.

my_dic['c']  # I accessed each element in my dictionary.

my_list = [100,200,300]   #1. Use a tuple if you have a collection of constant data that does not need to be changed.2.Use a list if you have a collection of variable data that may need to be changed.3.Use a tuple if you need speed.4.Use a list if you need mutability.

my_tuple = (100,200,300) #"The count() method returns the number of times a specific element appears in a tuple.""The index() method returns the first index of a specific element in a tuple.""You cannot use the append() method on a tuple because tuples are immutable.""Trying to append an element to a tuple will result in a TypeError exception."

my_list.append(400)

my_list

my_tuple.count(100)

my_tuple.index(100)

my_tuple.index(300)